Milestone desktop version
bertinkambale/My__Portfolio__1 pull request #5
Opened 2022-09-28 14:48 UTC by bertinkambale

For the fourth project in my portfolio website, I will:

- [ ] I  Used media queries to make sure that my website displays correctly on desktop screens.
- 
- [ ] General requirements
- [ ] Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- [ ]  Make sure that you used correct ([Github flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).
- [ ]  Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

2022-09-28 16:47 UTC, christianbiring1 requested changes
Hi @bertinkambale , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle:  
![almost](https://user-images.githubusercontent.com/97100091/192841108-6de1696b-ca93-419a-a522-10749dcb2895.gif)


## Highlights
- [ ] All linters checks are green
- [ ] Descriptive PR `tittle`

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Kindly makes sure you document your project in a professional way as well.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 16:47 UTC, christianbiring1 commented on index.html
>        <section class="main-header container">
- [ ] Kindly make sure you have the background images setup as you can see on the tempate.
![image](https://user-images.githubusercontent.com/97100091/192834055-72b681c4-fc08-4f63-83dc-74792e875a8a.png)
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/192834408-f9f3e6f3-b564-4e72-9373-34056f0570c1.png)

2022-09-28 16:47 UTC, christianbiring1 commented on index.html
>        <section class="main-header container">
- [ ] Kindly make sure you use the correct typo `fonts` as the template. `hint: You can click on the text in figma and on the right you will be able to see the correct font and color`

2022-09-28 16:47 UTC, christianbiring1 commented on index.html
> +          <h1>Tonic</h1>
- [ ] Kindly make sure there's only one header `h1` on the page. other headers can be `h2...6`

2022-09-28 16:47 UTC, christianbiring1 commented on index.html
>          </div>
- [ ] Kindly make sure you use enough `padding` and `margin` to make enough space on from the edge.
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/192836711-eabcac3d-b17d-46a9-8a8f-4e1aab2c598b.png)
Figma design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/192837039-f3818559-683f-4c6e-acbf-89739018a34c.png)

- [ ] Also consider making your images a little bit more responsive.

2022-09-28 16:47 UTC, christianbiring1 commented on style.css
>  .my-first-section h1 {
- [ ] Kindly make sure your project is responsive as you can see the way your page is overflowing on the right when it comes to the mobile version
![image](https://user-images.githubusercontent.com/97100091/192838386-7030e27f-d746-4428-a456-bef125b5449f.png)

2022-09-28 16:47 UTC, christianbiring1 commented on style.css
> +
- [ ] Kindly make sure your page is responsive on all the screen size
![image](https://user-images.githubusercontent.com/97100091/192839036-93625e3b-a887-4b5a-8b4b-9d683b601751.png)

2022-09-28 16:47 UTC, christianbiring1 commented on style.css
>  .my-first-section h1 {
![image](https://user-images.githubusercontent.com/97100091/192839409-c226e6ea-2f69-4fc5-aad3-c279554662f8.png)

2022-09-28 16:47 UTC, christianbiring1 commented on style.css
> +    width: 327px;
- [ ] Kindly make sure you stick to the image as possible as you can.
![image](https://user-images.githubusercontent.com/97100091/192840288-d58b99dd-5206-40df-b097-be6891d55699.png)
Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/192840650-613cf65e-acd4-4095-9d88-d750dfd66f5f.png)

2022-09-30 01:24 UTC, emmiiorji requested changes
Hi @bertinkambale, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Almost there](https://user-images.githubusercontent.com/20554583/193167972-8c715da2-4665-4902-b5c7-7131d5a89c15.gif)

 ## Good Highlights✔

- Some requested changes have been implemented
- Linter checks are passing
- Good commit messages
- Adherence to GitHub flow


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- In order to reduce cluttering on the project's home directory, I suggest that you organize all the project images into a single directory.
    
![image](https://user-images.githubusercontent.com/20554583/193169507-3c078940-5e9b-453a-9a5d-95c9a1bd8e07.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 01:24 UTC, emmiiorji commented on style.css
> +  }
You have done a great job at centring the get in touch button as requested by the previous reviewer. Kindly ensure that the size of the button and the text alignment match as well. Also notice that the black bar does not appear on the desktop view.

Your design:
![image](https://user-images.githubusercontent.com/20554583/193168864-a5f2012f-5858-4e25-b624-7394dd308315.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/193169076-375eb36b-5480-4d6b-a400-bd4dc445d714.png)

2022-09-30 01:24 UTC, emmiiorji commented on style.css
> +
As suggested by the previous reviewer, kindly ensure that you maintain the margins around the project cards as given on your chosen template design.

Your design:
![image](https://user-images.githubusercontent.com/20554583/193169846-9b5ad8fd-0bfe-4cf9-a8a9-0572722d3c10.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/193169775-20a853ec-379f-4e7b-9c8e-3865db52275b.png)

2022-09-30 08:23 UTC, Tadesse-Alemayehu requested changes
Hi @bertinkambale 

You have donned incredible job on making the changes requested by a previous reviewer 👏 
But there are still some which aren't addressed yet.

![request_change](https://user-images.githubusercontent.com/69077061/193225688-27fcd695-553b-40c6-b939-b7fc4f2c3d9a.gif)

 ## Highlights
- Most of the changes are implemented well. :heavy_check_mark: 
 - All linters checks are green  :heavy_check_mark: 
 - Descriptive PR tittle  :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 08:23 UTC, Tadesse-Alemayehu commented on index.html
>          </div>
- [ ] You are doing great, addressing the requested changes. Also, as the previous reviewer mention, you should consider adding padding and margins to your projects, so they will look like the one provided on Figma. This is part of the main project requirement.

## Your design 
![Screenshot from 2022-09-30 11-01-45](https://user-images.githubusercontent.com/69077061/193223632-416957c3-81d6-4067-b227-fb37e8ad5207.png)

## Figma design 
![Screenshot from 2022-09-30 11-02-39](https://user-images.githubusercontent.com/69077061/193223307-d3e5b849-5e25-4718-b00a-aa8f17bc1ab9.png)

2022-09-30 14:22 UTC, merged