Mile stone accessibility
bertinkambale/My__Portfolio__1 pull request #9
Opened 2022-10-05 18:19 UTC by bertinkambale

- Page Titles: No Issue Found
- Image Text Alternatives: No Issue Found
- Text Heading:No Issue Found
- Color Contrast: Issue Solved [Contrast](https://github.com/bertinkambale/My__Portfolio__1/compare/Mile_stone_Accessibility?expand=1#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L61)
- Resize:No Issue Found
- Interaction:No Issue Found
- Moving Content:No Issue Found
- Multimedia: Issue Solved [Alt](https://github.com/bertinkambale/My__Portfolio__1/compare/Mile_stone_Accessibility?expand=1#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L228)
- The basic Structure of the Page:No Issue Found

2022-10-05 18:50 UTC, christianbiring1 requested changes
Hi @bertinkambale , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![almost](https://user-images.githubusercontent.com/97100091/194138783-035b3812-d6b5-4892-84ee-6d686a57841b.gif)
## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` nad `summary`

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-05 18:50 UTC, christianbiring1 commented on index.html
> +            <label for="">
- [ ] On your mobile version, kindly make sure your page is not overlapping as it is the case and also consider reducing the `width` of your inputs so that your page may conform with the provided template
`hint: You can use the flexbox to place your input correctly.` 
- [ ] Kindly make sure you use the correct `typo: font` and `spacing: margin/padding` for your element
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/194135873-6c900386-e306-402a-8d0f-6815297ba9de.png)

Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/194136132-75177804-a4c2-40a5-b229-fb050bd7e45c.png)

2022-10-05 18:50 UTC, christianbiring1 commented on index.html
>            you see and have a project you need coded, don’t hestiate to contact
- [ ] Kindly make sure your page has a good `title` for `Accessibility` purpose.
`hint: You can use Bertin's portfolio`

2022-10-05 18:50 UTC, christianbiring1 commented on index.html
>                <img src="images/Separator-Bottom.svg" alt="" />
- [ ] Kindly make sure all your images have a descriptive `alt` attribute describing the image

2022-10-12 09:29 UTC, levy002 requested changes
## Hello @bertinkambale  , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-12 09:29 UTC, levy002 commented on index.html
> +          <li><img src="Icons/angellist.svg" alt="angellist_icon" /></li>
- [ ] The alternative text does not need to include the words "button", "link", "icon", or "image of". (Screen readers automatically provide that information.). Kindly remove it. :wink:

2022-10-12 09:29 UTC, levy002 commented on index.html
> +                <li><img src="Icons/angellist.svg" alt="angellist_icon2" /></li>
- [ ] The alternative text does not need to include the words "button", "link", "icon", or "image of". (Screen readers automatically provide that information.). Kindly remove it. :wink:

2022-10-12 14:05 UTC, sumairq approved these changes
### Hi Team , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-12 14:11 UTC, merged